services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-app
    ports:
      - "${APP_PORT}:80"
    volumes:
      - .:/var/www/html
    environment:
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
      - redis
    networks:
      - app_network

  db:
    image: mysql:8.0-oracle
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

  redis:
    image: redis:alpine
    container_name: redis-cache
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
